version: "3"
services:
  qdamono-server:
    container_name: qdamono-server
    image: qdamono-server:latest
    restart: always
    command: node /app/dist/main.js
    environment:
      - DATABASE_URL=mongodb://qdamono-mongo:27017/
      - SERVER_PORT=8080
      # - TLS_CERT_PATH=
      # - TLS_KEY_PATH=
      # - TLS_PASSPHRASE=
    ports:
      - 8080:8080
    depends_on:
      - qdamono-mongo

  qdamono-mongo:
    container_name: qdamono-mongo
    restart: always
    image: mongo

